ERROR - 2023-03-13 16:55:38 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Sistema-FECH\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Sistema-FECH\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Sistema-FECH\app\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Sistema-FECH\app\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
#6 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
#7 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
#8 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Sistema-FECH\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Sistema-FECH\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Sistema-FECH\app\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Sistema-FECH\app\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
#5 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
#6 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
#7 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Sistema-FECH\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-13 16:55:38 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Docente`', [], false)
 3 APPPATH\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-13 16:55:38 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Sistema-FECH\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Sistema-FECH\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Sistema-FECH\app\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Sistema-FECH\app\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
#6 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
#7 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
#8 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Sistema-FECH\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Sistema-FECH\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Sistema-FECH\app\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Sistema-FECH\app\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
#5 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
#6 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
#7 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Sistema-FECH\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-13 16:55:38 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Docente`', [], false)
 3 APPPATH\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:47 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:48 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:48 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:48 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:48 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:49 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:49 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:49 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:49 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:51 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:55:51 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:56:12 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:56:12 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:56:30 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:56:30 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:56:31 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:56:31 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:56:54 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:57:26 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:57:29 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:57:36 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:57:37 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:57:42 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:57:42 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:58:23 --> syntax error, unexpected identifier "s", expecting "]"
in APPPATH\Config\Database.php on line 44.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Config\\Database.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
 3 SYSTEMPATH\Debug\Toolbar\Collectors\Database.php(251): CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
 4 SYSTEMPATH\Debug\Toolbar\Collectors\Database.php(70): CodeIgniter\Debug\Toolbar\Collectors\Database->getConnections()
 5 SYSTEMPATH\Debug\Toolbar.php(65): CodeIgniter\Debug\Toolbar\Collectors\Database->__construct()
 6 SYSTEMPATH\Config\Services.php(723): CodeIgniter\Debug\Toolbar->__construct(Object(Config\Toolbar))
 7 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::toolbar(Object(Config\Toolbar), false)
 8 SYSTEMPATH\Config\BaseService.php(193): CodeIgniter\Config\BaseService::__callStatic('toolbar', [...])
 9 SYSTEMPATH\Config\Services.php(718): CodeIgniter\Config\BaseService::getSharedInstance('toolbar', null)
10 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::toolbar()
11 APPPATH\Config\Events.php(46): CodeIgniter\Config\BaseService::__callStatic('toolbar', [])
12 SYSTEMPATH\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
13 SYSTEMPATH\CodeIgniter.php(350): CodeIgniter\Events\Events::trigger('pre_system')
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:58:28 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:58:29 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:58:31 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:16 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:17 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:17 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:19 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:36 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:36 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:36 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:37 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:37 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:37 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:37 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 16:59:37 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:00:53 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:00:53 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:00:53 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:02:11 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:02:12 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:02:12 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:18 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:19 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:19 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:19 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:19 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:20 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:20 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:23 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:23 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:23 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:05:23 --> Class "CodeIgniter\Database\pdo\Connection" not found
in SYSTEMPATH\Database\Database.php on line 139.
 1 SYSTEMPATH\Database\Database.php(56): CodeIgniter\Database\Database->initDriver('pdo', 'CodeIgniter\\Database\\pdo\\Connection', [...])
 2 SYSTEMPATH\Database\Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 APPPATH\Controllers\PruebaController.php(11): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-13 17:06:53 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la relación «Docentse»
LINE 2: FROM &quot;Docentse&quot;
             ^ in C:\xampp\htdocs\Sistema-FECH\system\Database\Postgre\Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 147)
#1 C:\xampp\htdocs\Sistema-FECH\system\Database\Postgre\Connection.php(147): pg_query(Resource id #126, 'SELECT "id_Doce...')
#2 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(691): CodeIgniter\Database\Postgre\Connection->execute('SELECT "id_Doce...')
#3 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "id_Doce...')
#4 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT "id_Doce...', Array, false)
#5 C:\xampp\htdocs\Sistema-FECH\app\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Sistema-FECH\app\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
#7 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
#8 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
#9 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Sistema-FECH\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-13 17:06:53 --> pg_query(): Query failed: ERROR:  no existe la relación «Docentse»
LINE 2: FROM &quot;Docentse&quot;
             ^
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT "id_Docente"
FROM "Docentse"', [], false)
 2 APPPATH\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:07:18 --> syntax error, unexpected end of file
in APPPATH\Views\prueba.php on line 3.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('prueba', [], true)
 3 APPPATH\Controllers\PruebaController.php(13): view('prueba', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:07:21 --> syntax error, unexpected end of file
in APPPATH\Views\prueba.php on line 3.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('prueba', [], true)
 3 APPPATH\Controllers\PruebaController.php(13): view('prueba', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:07:22 --> syntax error, unexpected end of file
in APPPATH\Views\prueba.php on line 3.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('prueba', [], true)
 3 APPPATH\Controllers\PruebaController.php(13): view('prueba', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 17:07:22 --> syntax error, unexpected end of file
in APPPATH\Views\prueba.php on line 3.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('prueba', [], true)
 3 APPPATH\Controllers\PruebaController.php(13): view('prueba', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-13 17:07:42 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  la autentificaci�n password fall� para el usuario �postgres� in C:\xampp\htdocs\Sistema-FECH\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\Sistema-FECH\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT "id_Doce...', Array, false)
#5 C:\xampp\htdocs\Sistema-FECH\app\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Sistema-FECH\app\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
#7 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
#8 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
#9 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Sistema-FECH\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-13 17:07:42 --> Unable to connect to the database.
Main connection [postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  la autentificaci�n password fall� para el usuario �postgres�
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT "id_Docente"
FROM "Docente"', [], false)
 3 APPPATH\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-13 17:08:20 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: missing &quot;=&quot; after &quot;asd&quot; in connection info string in C:\xampp\htdocs\Sistema-FECH\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\Sistema-FECH\system\Database\Postgre\Connection.php(75): pg_connect('asd')
#2 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\Sistema-FECH\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT "id_Doce...', Array, false)
#5 C:\xampp\htdocs\Sistema-FECH\app\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Sistema-FECH\app\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
#7 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
#8 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
#9 C:\xampp\htdocs\Sistema-FECH\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Sistema-FECH\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-13 17:08:20 --> Unable to connect to the database.
Main connection [postgre]: pg_connect(): Unable to connect to PostgreSQL server: missing &quot;=&quot; after &quot;asd&quot; in connection info string
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT "id_Docente"
FROM "Docente"', [], false)
 3 APPPATH\Models\pruebaModel.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\PruebaController.php(12): App\Models\pruebaModel->obtener()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\PruebaController->prueba()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
